export const badges_data = [
  {
    id: '6881e4139d248f7ba0225379',
    title: 'First Smile',
    description: "Baby's very first genuine smile - a magical moment!",
    instruction: "Capture your baby's first real smile (not just gas!). Usually happens around 6-8 weeks.",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/first-smile.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 1,
    maxAge: 4,
  },
  {
    id: '6881e4139d248f7ba022537b',

    title: 'First Coo',
    description: "Baby's first vocal sounds besides crying",
    instruction: "Record your baby making their first 'ooh' and 'ahh' sounds. Usually around 2-3 months.",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/first-coo.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 1,
    maxAge: 4,
  },
  {
    id: '6881e4139d248f7ba022537d',

    title: 'Holds Head Up',
    description: 'Baby can lift and hold their head up independently',
    instruction: 'Document when your baby can hold their head up for at least 30 seconds during tummy time.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/head-up.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 2,
    maxAge: 5,
  },
  {
    id: '6881e4139d248f7ba022537f',

    title: 'Eyes Follow Objects',
    description: 'Baby can track moving objects with their eyes',
    instruction: 'Show your baby following a toy or your face with their eyes from side to side.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/eye-tracking.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 1,
    maxAge: 3,
  },
  {
    id: '6881e4139d248f7ba0225381',

    title: 'First Laugh',
    description: "Baby's first genuine giggle or laugh",
    instruction: 'Capture that precious first laugh! Usually happens around 3-4 months.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/first-laugh.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 2,
    maxAge: 6,
  },
  {
    id: '6881e4139d248f7ba0225383',

    title: 'Rolling Over',
    description: 'Baby rolls from tummy to back or back to tummy',
    instruction: "Document your baby's first successful roll! Usually happens around 4-6 months.",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/rolling.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 3,
    maxAge: 8,
  },
  {
    id: '6881e4139d248f7ba0225385',

    title: 'Sitting Up Unassisted',
    description: 'Baby can sit up without support for extended periods',
    instruction: 'Show your baby sitting independently for at least 1 minute without falling over.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/sitting.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 5,
    maxAge: 9,
  },
  {
    id: '6881e4139d248f7ba0225387',

    title: 'First Tooth',
    description: "Baby's very first tooth breaks through the gums",
    instruction: 'Take a photo of that precious first tooth! Usually around 6-7 months.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/first-tooth.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 4,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba0225389',

    title: 'Crawling',
    description: 'Baby moves forward on hands and knees',
    instruction: "Record your baby's first successful crawling movements, even if just a few 'steps'.",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/crawling.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 6,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba022538b',

    title: 'Pulling to Stand',
    description: 'Baby pulls themselves up to standing position',
    instruction: 'Document your baby pulling themselves up using furniture or crib rails.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/pulling-stand.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 7,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba022538d',

    title: 'First Word',
    description: 'Baby says their first recognizable word',
    instruction: "Record your baby saying their first clear word (like 'mama', 'dada', 'bye-bye').",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/first-word.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 8,
    maxAge: 15,
  },
  {
    id: '6881e4139d248f7ba022538f',

    title: 'Waving Bye-Bye',
    description: 'Baby waves goodbye on command or spontaneously',
    instruction: 'Capture your baby waving bye-bye when someone leaves or says goodbye.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/waving.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 7,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba0225391',

    title: 'First Steps',
    description: 'Baby takes their first independent steps',
    instruction: 'Record those magical first steps! Even 2-3 steps without support counts.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/first-steps.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 9,
    maxAge: 18,
  },
  {
    id: '6881e4139d248f7ba0225393',

    title: 'Two-Word Sentences',
    description: 'Baby combines two words to make simple sentences',
    instruction: "Document your baby saying phrases like 'more milk', 'go car', or 'big dog'.",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/two-words.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 15,
    maxAge: 24,
  },
  {
    id: '6881e4139d248f7ba0225395',

    title: 'Running',
    description: 'Child can run with coordination and balance',
    instruction: 'Show your toddler running smoothly without frequent falls.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/running.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 30,
  },
  {
    id: '6881e4139d248f7ba0225397',

    title: 'Potty Training Success',
    description: 'Child successfully uses the potty independently',
    instruction: "Celebrate your child's first successful potty use or staying dry for a full day!",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/potty.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba0225399',

    title: 'Jumping with Both Feet',
    description: 'Child jumps up with both feet leaving the ground',
    instruction: 'Record your child jumping up and down or off a low step with both feet together.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/jumping.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 20,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba022539b',

    title: 'Counting to 10',
    description: 'Child can count from 1 to 10 independently',
    instruction: "Record your child counting to 10 without help (pronunciation doesn't have to be perfect!).",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/counting.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba022539d',

    title: 'Pedaling a Tricycle',
    description: 'Child can pedal and steer a tricycle',
    instruction: 'Show your child successfully riding a tricycle using the pedals.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/tricycle.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba022539f',

    title: 'Writing Own Name',
    description: 'Child can write their first name independently',
    instruction: 'Document your child writing their name, even if some letters are backwards or wobbly!',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/writing-name.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253a1',

    title: 'Riding a Bicycle',
    description: 'Child rides a bicycle without training wheels',
    instruction: 'Capture the moment your child rides a bike independently without training wheels!',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/bicycle.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 42,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba02253a3',

    title: 'Tying Shoes',
    description: 'Child can tie their own shoelaces',
    instruction: 'Show your child successfully tying their shoes with a bow that stays tied.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/tying-shoes.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 48,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba02253a5',

    title: 'Swimming Independently',
    description: 'Child swims short distances without assistance',
    instruction: 'Record your child swimming at least 10 feet without flotation devices or help.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/swimming.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba02253a7',

    title: 'Reading First Book',
    description: 'Child reads their first book independently',
    instruction: 'Document your child reading a simple book (like early readers) all by themselves.',
    category: 'milestone',
    iconUrl: 'https://example.com/icons/reading.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 48,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba02253a9',

    title: 'Lost First Tooth',
    description: 'Child loses their first baby tooth',
    instruction: "Celebrate this rite of passage! Don't forget to leave it for the tooth fairy.",
    category: 'milestone',
    iconUrl: 'https://example.com/icons/lost-tooth.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 60,
    maxAge: 96,
  },
  {
    id: '6881e4139d248f7ba02253ab',

    title: 'First Solid Food',
    description: 'Baby tries their first solid food',
    instruction: "Document baby's first taste of solid food - capture that funny facial expression!",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/first-solid.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 4,
    maxAge: 8,
  },
  {
    id: '6881e4139d248f7ba02253ad',

    title: 'Self-Feeding with Spoon',
    description: 'Baby successfully feeds themselves with a spoon',
    instruction: 'Show your baby getting food in their mouth using a spoon (mess is expected!).',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/spoon-feeding.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 12,
    maxAge: 20,
  },
  {
    id: '6881e4139d248f7ba02253af',

    title: 'Drinking from a Cup',
    description: 'Baby drinks from an open cup without spilling',
    instruction: 'Document your baby successfully drinking from a regular cup with minimal spillage.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/cup-drinking.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 10,
    maxAge: 18,
  },
  {
    id: '6881e4139d248f7ba02253b1',

    title: 'Using Fork Properly',
    description: 'Child uses a fork to eat food independently',
    instruction: 'Show your child successfully using a fork to pick up and eat food.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/fork-eating.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 30,
  },
  {
    id: '6881e4139d248f7ba02253b3',

    title: 'Eating Vegetables',
    description: 'Child willingly eats vegetables without fuss',
    instruction: 'Celebrate when your child eats vegetables without being forced or bribed!',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/eating-veggies.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 12,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253b5',

    title: 'Sleeping Through the Night',
    description: 'Baby sleeps for 6+ hours without waking',
    instruction: 'Document when your baby sleeps for at least 6 consecutive hours - a parent victory!',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/sleeping-night.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 2,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba02253b7',

    title: 'Bedtime Routine Master',
    description: 'Child follows bedtime routine independently',
    instruction: 'Show your child brushing teeth, putting on pajamas, and getting ready for bed alone.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/bedtime-routine.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba02253b9',

    title: 'Nap Time Champion',
    description: 'Child takes regular, restorative naps',
    instruction: 'Document your child having a good nap routine and sleeping peacefully during naptime.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/nap-time.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 6,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba02253bb',

    title: 'First Bath Enjoyment',
    description: 'Baby enjoys bath time without crying',
    instruction: 'Capture your baby happily playing or relaxing during bath time.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/bath-fun.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 1,
    maxAge: 6,
  },
  {
    id: '6881e4139d248f7ba02253bd',

    title: 'Brushing Teeth',
    description: 'Child brushes their teeth independently',
    instruction: 'Show your child brushing their teeth properly without constant reminders.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/brushing-teeth.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba02253bf',

    title: 'Washing Hands',
    description: 'Child washes hands properly on their own',
    instruction: 'Document your child washing hands with soap and water without being reminded.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/washing-hands.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 15,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba02253c1',

    title: 'Getting Dressed',
    description: 'Child puts on clothes independently',
    instruction: 'Show your child putting on shirts, pants, or socks all by themselves.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/getting-dressed.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 20,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba02253c3',

    title: 'First Puzzle Piece',
    description: 'Baby puts their first puzzle piece in correctly',
    instruction: 'Document your baby successfully placing a puzzle piece in the right spot.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/puzzle-piece.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 12,
    maxAge: 24,
  },
  {
    id: '6881e4139d248f7ba02253c5',

    title: 'Building Block Tower',
    description: 'Child builds a tower of 5+ blocks',
    instruction: "Show your child stacking blocks into a tower that's at least 5 blocks high.",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/block-tower.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 30,
  },
  {
    id: '6881e4139d248f7ba02253c7',

    title: 'Coloring Inside Lines',
    description: 'Child colors mostly within the lines',
    instruction: "Document your child's artwork where they color mostly inside the lines.",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/coloring.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253c9',

    title: 'Completing a Jigsaw Puzzle',
    description: 'Child completes an age-appropriate jigsaw puzzle',
    instruction: 'Show your child finishing a puzzle with at least 12-20 pieces.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/jigsaw-puzzle.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba02253cb',

    title: 'First Playground Visit',
    description: "Baby's first trip to the playground",
    instruction: "Document your baby's first playground adventure - swings, slides, or sandbox!",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/playground.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 6,
    maxAge: 18,
  },
  {
    id: '6881e4139d248f7ba02253cd',

    title: 'Going Down a Slide',
    description: 'Child goes down a slide independently',
    instruction: 'Record your child sliding down a playground slide all by themselves.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/slide.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba02253cf',

    title: 'Swinging Independently',
    description: 'Child swings on a swing without help',
    instruction: 'Show your child pumping their legs and swinging all by themselves.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/swinging.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba02253d1',

    title: 'Beach Day Explorer',
    description: 'Child enjoys their first beach experience',
    instruction: 'Document your child playing in the sand, waves, or just enjoying the beach.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/beach.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 6,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253d3',

    title: 'First Day of Daycare',
    description: "Child's first day at daycare or preschool",
    instruction: 'Capture this milestone moment - the beginning of their educational journey!',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/first-school.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 12,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253d5',

    title: 'Learning ABCs',
    description: 'Child recites the alphabet independently',
    instruction: 'Record your child saying the ABCs from A to Z without help.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/abc.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253d7',

    title: 'Recognizing Colors',
    description: 'Child correctly identifies basic colors',
    instruction: 'Show your child naming at least 5 basic colors correctly.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/colors.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba02253d9',

    title: 'Drawing a Person',
    description: 'Child draws a recognizable human figure',
    instruction: "Document your child's first drawing that looks like a person (head, body, arms, legs).",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/drawing-person.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253db',

    title: 'First Video Call',
    description: 'Baby participates in their first video call',
    instruction: 'Document your baby on a video call with grandparents or family members.',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/video-call.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 3,
    maxAge: 24,
  },
  {
    id: '6881e4139d248f7ba02253dd',

    title: 'Taking Photos',
    description: 'Child takes their first photos',
    instruction: 'Give your child a camera (toy or real) and let them take their own pictures!',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/taking-photos.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253df',

    title: 'First Halloween Costume',
    description: "Baby's first Halloween in costume",
    instruction: 'Capture your baby in their adorable first Halloween costume!',
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/halloween.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 1,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba02253e1',

    title: 'First Birthday Celebration',
    description: "Child's first birthday party",
    instruction: "Document the joy and excitement of your child's very first birthday celebration.",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/first-birthday.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 12,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba02253e3',

    title: 'Christmas Morning Magic',
    description: 'Child experiences Christmas morning',
    instruction: "Capture the wonder and excitement of Christmas morning through your child's eyes.",
    category: 'daily_life',
    iconUrl: 'https://example.com/icons/christmas.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 6,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba02253e5',

    title: 'Social Smiling',
    description: 'Baby smiles in response to others',
    instruction: 'Document your baby smiling back when you smile at them or talk to them.',
    category: 'social',
    iconUrl: 'https://example.com/icons/social-smile.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 1,
    maxAge: 4,
  },
  {
    id: '6881e4139d248f7ba02253e7',

    title: 'Playing Peek-a-Boo',
    description: 'Baby enjoys and responds to peek-a-boo games',
    instruction: 'Show your baby laughing and enjoying peek-a-boo games with you.',
    category: 'social',
    iconUrl: 'https://example.com/icons/peekaboo.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 4,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba02253e9',

    title: 'Stranger Awareness',
    description: 'Baby shows appropriate wariness of strangers',
    instruction: 'Document your baby showing normal stranger anxiety around 8-10 months.',
    category: 'social',
    iconUrl: 'https://example.com/icons/stranger-awareness.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 6,
    maxAge: 15,
  },
  {
    id: '6881e4139d248f7ba02253eb',

    title: 'Imitating Actions',
    description: 'Baby copies simple actions they see',
    instruction: 'Show your baby imitating clapping, waving, or other simple gestures.',
    category: 'social',
    iconUrl: 'https://example.com/icons/imitating.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 8,
    maxAge: 18,
  },
  {
    id: '6881e4139d248f7ba02253ed',

    title: 'Sharing Toys',
    description: 'Child willingly shares toys with others',
    instruction: 'Document your child sharing a toy or snack with another child or adult.',
    category: 'social',
    iconUrl: 'https://example.com/icons/sharing.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba02253ef',

    title: 'Playing with Other Children',
    description: 'Child engages in parallel or cooperative play',
    instruction: 'Show your child playing alongside or with other children happily.',
    category: 'social',
    iconUrl: 'https://example.com/icons/playing-together.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba02253f1',

    title: 'Following Simple Rules',
    description: 'Child follows basic rules and instructions',
    instruction: "Document your child following simple rules like 'no touching' or 'sit down'.",
    category: 'social',
    iconUrl: 'https://example.com/icons/following-rules.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba02253f3',

    title: 'Showing Empathy',
    description: 'Child shows concern for others who are upset',
    instruction: 'Capture your child comforting someone who is sad or hurt.',
    category: 'social',
    iconUrl: 'https://example.com/icons/empathy.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 20,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba02253f5',

    title: 'Using Please and Thank You',
    description: 'Child uses basic polite words appropriately',
    instruction: "Record your child saying 'please' and 'thank you' without being prompted.",
    category: 'social',
    iconUrl: 'https://example.com/icons/manners.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 20,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba02253f7',

    title: 'Making Friends',
    description: 'Child actively tries to befriend other children',
    instruction: 'Show your child approaching and trying to play with new children.',
    category: 'social',
    iconUrl: 'https://example.com/icons/making-friends.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253f9',

    title: 'Helping with Chores',
    description: 'Child helps with age-appropriate household tasks',
    instruction: 'Document your child helping with simple chores like putting toys away or feeding pets.',
    category: 'social',
    iconUrl: 'https://example.com/icons/helping-chores.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253fb',

    title: 'Showing Affection',
    description: 'Child spontaneously shows affection to family',
    instruction: "Capture your child giving hugs, kisses, or saying 'I love you' on their own.",
    category: 'social',
    iconUrl: 'https://example.com/icons/showing-affection.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 12,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba02253fd',

    title: 'Taking Turns',
    description: 'Child waits their turn during games or activities',
    instruction: 'Show your child patiently waiting their turn in a game or on playground equipment.',
    category: 'social',
    iconUrl: 'https://example.com/icons/taking-turns.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba02253ff',

    title: 'Apologizing Sincerely',
    description: "Child apologizes when they've done something wrong",
    instruction: "Document your child saying 'sorry' or apologizing after making a mistake.",
    category: 'social',
    iconUrl: 'https://example.com/icons/apologizing.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225401',

    title: 'Including Others',
    description: 'Child invites others to join their play',
    instruction: 'Show your child asking another child to play or including them in activities.',
    category: 'social',
    iconUrl: 'https://example.com/icons/including-others.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba0225403',

    title: 'Resolving Conflicts',
    description: 'Child solves disagreements peacefully',
    instruction: 'Document your child working out a problem with another child using words.',
    category: 'social',
    iconUrl: 'https://example.com/icons/conflict-resolution.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba0225405',

    title: 'Understanding Emotions',
    description: 'Child identifies and names different emotions',
    instruction: 'Show your child correctly identifying emotions like happy, sad, angry, or excited.',
    category: 'social',
    iconUrl: 'https://example.com/icons/emotions.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225407',

    title: 'Comforting Others',
    description: 'Child actively comforts someone who is upset',
    instruction: 'Capture your child offering comfort, a hug, or kind words to someone who is sad.',
    category: 'social',
    iconUrl: 'https://example.com/icons/comforting.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba0225409',

    title: 'Being a Good Sport',
    description: 'Child handles winning and losing gracefully',
    instruction: 'Document your child being a good winner or loser during games.',
    category: 'social',
    iconUrl: 'https://example.com/icons/good-sport.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba022540b',

    title: 'Leadership Skills',
    description: 'Child takes initiative in group activities',
    instruction: 'Show your child leading a game, organizing play, or taking charge of a group activity.',
    category: 'social',
    iconUrl: 'https://example.com/icons/leadership.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 42,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba022540d',

    title: 'Tummy Time Champion',
    description: 'Baby enjoys and tolerates tummy time',
    instruction: 'Document your baby happily spending time on their tummy, building neck strength.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/tummy-time.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 0,
    maxAge: 6,
  },
  {
    id: '6881e4139d248f7ba022540f',

    title: 'Reaching for Toys',
    description: 'Baby intentionally reaches for objects',
    instruction: 'Show your baby deliberately reaching for toys or objects they want.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/reaching.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 2,
    maxAge: 6,
  },
  {
    id: '6881e4139d248f7ba0225411',

    title: 'Grasping Objects',
    description: 'Baby grasps and holds objects in their hands',
    instruction: 'Document your baby successfully grabbing and holding onto toys or objects.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/grasping.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 3,
    maxAge: 8,
  },
  {
    id: '6881e4139d248f7ba0225413',

    title: 'Transferring Objects',
    description: 'Baby moves objects from one hand to the other',
    instruction: 'Show your baby passing a toy or object from one hand to the other hand.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/transferring.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 5,
    maxAge: 10,
  },
  {
    id: '6881e4139d248f7ba0225415',

    title: 'Pincer Grasp',
    description: 'Baby picks up small objects with thumb and finger',
    instruction: 'Document your baby picking up small items like cheerios using thumb and forefinger.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/pincer-grasp.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 8,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba0225417',

    title: 'Clapping Hands',
    description: 'Baby claps their hands together',
    instruction: 'Show your baby clapping their hands together, either imitating you or spontaneously.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/clapping.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 6,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba0225419',

    title: 'Cruising Furniture',
    description: 'Baby walks while holding onto furniture',
    instruction: 'Document your baby walking sideways while holding onto couches, tables, or walls.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/cruising.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 8,
    maxAge: 15,
  },
  {
    id: '6881e4139d248f7ba022541b',

    title: 'Walking Backwards',
    description: 'Child walks backwards with control',
    instruction: 'Show your child confidently walking backwards without falling.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/walking-backwards.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 30,
  },
  {
    id: '6881e4139d248f7ba022541d',

    title: 'Standing on One Foot',
    description: 'Child balances on one foot briefly',
    instruction: 'Document your child standing on one foot for at least 3-5 seconds.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/one-foot.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba022541f',

    title: 'Hopping on One Foot',
    description: 'Child hops on one foot multiple times',
    instruction: 'Show your child hopping on one foot at least 3-5 times in a row.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/hopping.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225421',

    title: 'Skipping',
    description: 'Child skips with alternating feet',
    instruction: 'Document your child skipping with the proper alternating foot pattern.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/skipping.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 42,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba0225423',

    title: 'Galloping',
    description: 'Child gallops like a horse',
    instruction: 'Show your child galloping with the leading foot pattern like a horse.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/galloping.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225425',

    title: 'Scribbling',
    description: 'Child makes marks on paper with crayons',
    instruction: "Document your child's first scribbles and artistic expressions on paper.",
    category: 'physical',
    iconUrl: 'https://example.com/icons/scribbling.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 12,
    maxAge: 24,
  },
  {
    id: '6881e4139d248f7ba0225427',

    title: 'Stacking Blocks',
    description: 'Child stacks 3+ blocks in a tower',
    instruction: 'Show your child successfully stacking at least 3 blocks on top of each other.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/stacking-blocks.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 30,
  },
  {
    id: '6881e4139d248f7ba0225429',

    title: 'Using Scissors',
    description: 'Child cuts paper with safety scissors',
    instruction: 'Document your child successfully cutting paper with child-safe scissors.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/scissors.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba022542b',

    title: 'Drawing Circles',
    description: 'Child draws recognizable circles',
    instruction: 'Show your child drawing circles that are mostly round and closed.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/drawing-circles.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba022542d',

    title: 'Drawing Straight Lines',
    description: 'Child draws straight lines intentionally',
    instruction: 'Document your child drawing relatively straight lines on purpose.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/straight-lines.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 20,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba022542f',

    title: 'Threading Beads',
    description: 'Child threads large beads onto string',
    instruction: 'Show your child successfully threading large beads onto a string or shoelace.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/threading-beads.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225431',

    title: 'Rolling a Ball',
    description: 'Child rolls a ball to another person',
    instruction: 'Document your child rolling a ball back and forth with you or another child.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/rolling-ball.png',
    isActive: true,
    isCustom: false,
    difficulty: 'easy',
    minAge: 12,
    maxAge: 24,
  },
  {
    id: '6881e4139d248f7ba0225433',

    title: 'Throwing a Ball',
    description: 'Child throws a ball with intention',
    instruction: 'Show your child throwing a ball toward a target or another person.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/throwing-ball.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba0225435',

    title: 'Catching a Ball',
    description: 'Child catches a ball with both hands',
    instruction: 'Document your child successfully catching a ball thrown gently to them.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/catching-ball.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225437',

    title: 'Kicking a Ball',
    description: 'Child kicks a ball with accuracy',
    instruction: 'Show your child kicking a ball in a specific direction or toward a goal.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/kicking-ball.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 20,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba0225439',

    title: 'Bouncing a Ball',
    description: 'Child bounces and catches a ball',
    instruction: 'Document your child bouncing a ball and catching it multiple times.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/bouncing-ball.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 42,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba022543b',

    title: 'Climbing Stairs',
    description: 'Child climbs stairs independently',
    instruction: 'Show your child going up or down stairs without holding hands (but stay close!).',
    category: 'physical',
    iconUrl: 'https://example.com/icons/climbing-stairs.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba022543d',

    title: 'Monkey Bars',
    description: 'Child crosses monkey bars hand over hand',
    instruction: 'Document your child successfully crossing monkey bars using arm strength.',
    category: 'physical',
    iconUrl: 'https://example.com/icons/monkey-bars.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 48,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba022543f',

    title: 'Object Permanence',
    description: 'Baby looks for hidden objects',
    instruction: 'Show your baby searching for a toy after you hide it under a blanket.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/object-permanence.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 6,
    maxAge: 12,
  },
  {
    id: '6881e4139d248f7ba0225441',

    title: 'Cause and Effect',
    description: 'Baby understands that actions have consequences',
    instruction: 'Document your baby deliberately dropping toys to see what happens or pressing buttons.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/cause-effect.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 8,
    maxAge: 15,
  },
  {
    id: '6881e4139d248f7ba0225443',

    title: 'Shape Recognition',
    description: 'Child identifies basic shapes',
    instruction: 'Show your child correctly naming circles, squares, triangles, and rectangles.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/shapes.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba0225445',

    title: 'Sorting by Color',
    description: 'Child sorts objects by color',
    instruction: 'Document your child sorting toys, blocks, or objects into groups by color.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/sorting-colors.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 20,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba0225447',

    title: 'Sorting by Size',
    description: 'Child sorts objects by size',
    instruction: 'Show your child arranging objects from biggest to smallest or grouping by size.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/sorting-size.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba0225449',

    title: 'Pattern Recognition',
    description: 'Child identifies and continues simple patterns',
    instruction: 'Document your child completing patterns like red-blue-red-blue or big-small-big-small.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/patterns.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba022544b',

    title: 'Memory Game Master',
    description: 'Child plays memory games successfully',
    instruction: 'Show your child playing and succeeding at memory matching games.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/memory-game.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba022544d',

    title: 'Following Directions',
    description: 'Child follows 2-3 step instructions',
    instruction: "Document your child following multi-step directions like 'get your shoes and put them by the door'.",
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/following-directions.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba022544f',

    title: 'Understanding Opposites',
    description: 'Child identifies opposite concepts',
    instruction: 'Show your child correctly identifying opposites like big/small, hot/cold, up/down.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/opposites.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba0225451',

    title: 'Problem Solving',
    description: 'Child solves age-appropriate problems',
    instruction: 'Document your child figuring out how to reach a toy, open a container, or solve a puzzle.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/problem-solving.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 18,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225453',

    title: 'Pretend Play',
    description: 'Child engages in imaginative play',
    instruction: 'Show your child pretending - feeding a doll, talking on a toy phone, or playing house.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/pretend-play.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 15,
    maxAge: 36,
  },
  {
    id: '6881e4139d248f7ba0225455',

    title: 'Understanding Time',
    description: 'Child grasps basic time concepts',
    instruction: "Document your child understanding 'before/after', 'yesterday/today/tomorrow', or daily routines.",
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/understanding-time.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 30,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225457',

    title: 'Matching Games',
    description: 'Child matches identical objects or pictures',
    instruction: 'Show your child successfully matching pairs in games or puzzles.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/matching.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 18,
    maxAge: 42,
  },
  {
    id: '6881e4139d248f7ba0225459',

    title: 'Understanding Quantities',
    description: 'Child compares more/less and few/many',
    instruction: 'Document your child correctly identifying which group has more or less items.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/quantities.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 48,
  },
  {
    id: '6881e4139d248f7ba022545b',

    title: 'Simple Addition',
    description: 'Child adds small numbers with objects',
    instruction: 'Show your child counting objects and figuring out simple addition like 2+1=3.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/addition.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 42,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba022545d',

    title: 'Rhyming Words',
    description: 'Child identifies or creates rhyming words',
    instruction: "Document your child recognizing that words like 'cat' and 'bat' rhyme.",
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/rhyming.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba022545f',

    title: 'Story Sequencing',
    description: 'Child puts story events in order',
    instruction: 'Show your child arranging pictures to tell a story in the correct sequence.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/story-sequence.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 72,
  },
  {
    id: '6881e4139d248f7ba0225461',

    title: 'Critical Thinking',
    description: "Child asks 'why' and 'how' questions",
    instruction: 'Document your child asking thoughtful questions about how things work or why things happen.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/critical-thinking.png',
    isActive: true,
    isCustom: false,
    difficulty: 'medium',
    minAge: 24,
    maxAge: 60,
  },
  {
    id: '6881e4139d248f7ba0225463',

    title: 'Creative Storytelling',
    description: 'Child creates original stories',
    instruction: 'Record your child making up their own stories with characters and plot.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/storytelling.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 36,
    maxAge: 84,
  },
  {
    id: '6881e4139d248f7ba0225465',

    title: 'Scientific Thinking',
    description: 'Child makes predictions and tests them',
    instruction: 'Show your child making a guess about what will happen and then testing it out.',
    category: 'cognitive',
    iconUrl: 'https://example.com/icons/scientific-thinking.png',
    isActive: true,
    isCustom: false,
    difficulty: 'hard',
    minAge: 42,
    maxAge: 84,
  },
];
